config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ネスト(入れ子)した形に変更 + フォロー一覧、フォロワー一覧の画面も用意
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:index]
  end

  resources :memos do
    collection do
    post :confirm
    # post :new, path: :new, as: :new, action: :back
  end
    resources :memo_comments, only: [:create, :destroy]
    resource :favorites, only: [:index, :create, :destroy]
  end

  get 'searchs/search' => 'searchs#search', as: :search

  resources :homes, only: [:top ,:show]
  root to: 'homes#top'
  get '/home/about' => 'homes#show', as: :about
  resources :maps, only: [:create, :index, :show, :edit, :create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memos ,dependent: :destroy
  has_many :memo_comments ,dependent: :destroy
  has_many :favorites ,dependent: :destroy

  attachment :profile_image
  validates :name, presence: true, length: { in: 1..15 }
  validates :introduction, length: { maximum: 50 }


  # フォローする側、される側ふた通りの中間テーブルの名前を再定義
  # has_many :active_relationships, class_name: "Relationship"
  # has_many :passive_relationships, class_name: "Relationship"
  # ↑はNG 親モデルの外部キーがなんなのかという情報が足りない

  # :foreign_key - 参照先のテーブルの外部キーのカラム名を指定できる

  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(method,word)
    if method == "1" #部分一致
      @users = User.where("name LIKE?","%#{word}%")
    elsif method == "2" #完全一致
      @users = User.where("name LIKE?","#{word}")
    elsif method == "3" #前方一致
      @users = User.where("name LIKE?","#{word}%")
    elsif method == "4" #後方一致
      @users = User.where("name LIKE?","%#{word}")
    else
      @users = User.all
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show ,:edit]
  def index
    @newmemo = Memo.new
    @users = User.search(params[:method],params[:word])
  end

  def show
    @newmemo = Memo.new
    @user = User.find(params[:id])
    @memos = @user.memos
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集しました！"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follows
    @newmemo = Memo.new
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    @newmemo = Memo.new
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render 'headfoot/header' %>

<div class="container">
  <div class="row">
  <!-- サイドバー -->
    <h1>USER EDIT</h1>

    <!-- 編集フォーマット -->
    <% if @user.errors.any? %>
      <h2><%= @user.errors.count %> errors prohibited this book from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>

    <%= form_for(@user) do |f| %>

      <h4>名前</h4>
      <%= f.text_field :name %>

      <h4>画像</h4>
      <%= f.attachment_field :profile_image %>

      <h4>自己紹介</h4>
      <%= f.text_area :introduction %>

      <br><%= f.submit 'Create Book' %></br>
    <% end %>
  </div>
<!-- footer -->
<%= render 'headfoot/footer' %>
</div>

app/views/users/followers.html.erb
<body class="fourth-visual">

<%= render 'headfoot/header' %>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'memos/new', user: current_user, newmemo: @newmemo %>
    </div>

    <div class="col-xs-8">
      <h2>フォロワー一覧</h2>

      <table class="table">
        <thead>
          <tr>
            <th>ユーザー画像</th>
            <th>お名前</th>
            <th>フォロー</th>
            <th>フォロワー</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user,:profile_image, :fill, 50, 50, format: 'png', fallback: "no_image.jpg", size:'50x50' %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= user.followings.count %>
              </td>
              <td>
                <%= user.followers.count %>
              </td>
              <td>
                <%= link_to "詳細", user_path(user.id) %>
              </td>
              <td>
              <!-- フォロー -->
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                    <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn smoothScroll anime_test_2" %>
                <% else %>
                    <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn smoothScroll anime_test" %>
                <% end %>
              <% end %>
              <!-- フォロー -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render 'headfoot/topback' %>
  <%= render 'headfoot/footer' %>
</div>
</body>

app/views/users/follows.html.erb
<%= render 'headfoot/header' %>

<div class="container">
  <div class="row">

    <div class="col-xs-4">
      <%= render 'memos/new', user: current_user, newmemo: @newmemo %>
    </div>
    <div class="col-xs-8">
      <h1>フォロー一覧</h1>

      <table class="table">
        <thead>
          <tr>
            <th>ユーザー画像</th>
            <th>お名前</th>
            <th>フォロー</th>
            <th>フォロワー</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user,:profile_image, :fill, 50, 50, format: 'png', fallback: "no_image.jpg", size:'50x50' %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= user.followings.count %>
              </td>
              <td>
                <%= user.followers.count %>
              </td>
              <td>
                <%= link_to "詳細", user_path(user.id) %>
              </td>
              <td>
              <!-- フォロー -->
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                    <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn smoothScroll anime_test_2" %>
                <% end %>
              <% end %>
              <!-- フォロー -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render 'headfoot/topback' %>
  <%= render 'headfoot/footer' %>
</div>

app/views/users/index.html.erb
<%= render 'headfoot/header' %>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'memos/new', user: current_user, newmemo: @newmemo %>
    </div>

    <div class="col-xs-8">
      <h2>登録ユーザー一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>ユーザー画像</th>
            <th>お名前</th>
            <th>フォロー</th>
            <th>フォロワー</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td>
                <%= attachment_image_tag user,:profile_image, :fill, 50, 50, format: 'png', fallback: "no_image.jpg", size:'50x50' %>
              </td>
              <td>
                <%= user.name %>
              </td>
              <td>
                <%= user.followings.count %>
              </td>
              <td>
                <%= user.followers.count %>
              </td>
              <td>
                <%= link_to "詳細", user_path(user.id), class: "btn smoothScroll anime" %>
              </td>
              <td>
              <!-- フォロー -->
              <% if current_user != user %>
                <% if user.followed_by?(current_user) %>
                    <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn smoothScroll anime_test_2" %>
                <% else %>
                    <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn smoothScroll anime_test" %>
                <% end %>
              <% end %>
              <!-- フォロー -->
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render 'headfoot/topback' %>
  <%= render 'headfoot/footer' %>
</div>

app/views/users/show.html.erb
<%= render 'headfoot/header' %>

<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'memos/new', user: @user, newmemo: @newmemo %>
    </div>

    <div class="col-xs-8">
      <h2>user投稿一覧</h2>
      <table class="table">
        <thead>
          <tr>
            <th>タイトル</th>
            <th>内容詳細</th>
            <th>イイね！</th>
          </tr>
        </thead>

        <tbody>
           <% @memos.each do |memo| %>
            <tr>
              <td>
                <%= link_to memo_path(memo.id) do %>
                 <%= memo.title %>
                <% end %>
              </td>
              <td>
                 <%= memo.body %>
              </td>
              <td>
                <div id="likes_buttons_<%= memo.id %>">
                  <%= render 'memos/favo', memo: memo %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render 'headfoot/topback' %>
  <%= render 'headfoot/footer' %>
</div>