config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ネスト(入れ子)した形に変更 + フォロー一覧、フォロワー一覧の画面も用意
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:index]
  end

  resources :memos do
    collection do
    post :confirm
    # post :new, path: :new, as: :new, action: :back
  end
    resources :memo_comments, only: [:create, :destroy]
    resource :favorites, only: [:index, :create, :destroy]
  end

  get 'searchs/search' => 'searchs#search', as: :search

  resources :homes, only: [:top ,:show]
  root to: 'homes#top'
  get '/home/about' => 'homes#show', as: :about
  resources :maps, only: [:create, :index, :show, :edit, :create, :destroy]
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  has_many :memo_comments, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(method,word)
    if method == "1" #部分一致
      @memos = Memo.where("title LIKE?","%#{word}%")
    elsif method == "2" #完全一致
      @memos = Memo.where("title LIKE?","#{word}")
    elsif method == "3" #前方一致
      @memos = Memo.where("title LIKE?","#{word}%")
    elsif method == "4" #後方一致
      @memos = Memo.where("title LIKE?","%#{word}")
    else
      @memos = Memo.all
    end
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit]
  def new
    @newmemo = Memo.new
  end

  def confirm
    @newmemo = Memo.new(memo_params)
    return if @newmemo.valid?
  end

  def back
    @newmemo = Memo.new(memo_params)
    render :new
  end

  def create
    @newmemo = Memo.new(memo_params)
    @newmemo.user_id = current_user.id
    if @newmemo.save
      flash[:notice] = "新規登録しました！"
      redirect_to memo_path(@newmemo)
    else
      @memos = Memo.all
      render :index
    end
  end

  def index
    @newmemo = Memo.new
    @memos = Memo.search(params[:method],params[:word])
  end

  def show
    @newmemo = Memo.new
    @memo = Memo.find(params[:id])
    @user = @memo.user
    @memo_comment = MemoComment.new

    comments = @memo.memo_comments
    ratessum = 0
    comments.each do |comment|
      ratessum += comment.rates
    end
    @ave = comments.length == 0 ? 0
    : ratessum / comments.length
  end


  def edit
    @memo = Memo.find(params[:id])
    if @memo.user_id != current_user.id
      redirect_to memos_path
    else
      render :edit
    end
  end
  def update
    @memo = Memo.find(params[:id])
    if @memo.update(memo_params)
      flash[:notice] = "編集しました！"
      redirect_to memo_path(@memo)
    else
      render :edit
    end
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    flash[:notice] = "削除しました！"
    redirect_to memos_path
  end

  private
  def memo_params
    params.require(:memo).permit(:title, :body ,:user_id)
  end
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/views/memos/_comment.html.erb
<% memo.memo_comments.each do |memo_comment| %>
<tr>
  <td><%= attachment_image_tag memo_comment.user ,:profile_image, :fill, 50, 50, format: 'png', fallback: "no_image.jpg", size:'50x50' %></td>
  <td><%= memo_comment.user.name %></td>
  <td><%= memo_comment.rates %></td>
  <td><%= memo_comment.created_at.strftime('%Y/%m/%d') %></td>
  <td><%= memo_comment.comment %></td>
  <td>
    <% if memo_comment.user_id == current_user.id %>
      <%= link_to "コメントを削除", memo_memo_comment_path(memo.id, memo_comment.id), method: :delete, remote: true %>
    <% end %>
  </td>
</tr>
<% end %>

app/views/memos/_favo.html.erb
<% if user_signed_in? %>
  <% if memo.favorited_by?(current_user) %>
    <%= link_to memo_favorites_path(memo), method: :delete, remote: true do %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span>
    <% end %>
  <% else %>
    <%= link_to memo_favorites_path(memo), method: :post, remote: true do %>
      <span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: gray;"></span>
    <% end %>
  <% end %>
  <%= memo.favorites.count %> イイね！
<% end %>

app/views/memos/_new.html.erb
<h2>ユーザー情報</h2>

<table class="table">
  <thead>
    <tr>
      <th>
        <%= attachment_image_tag user,:profile_image, :fill, 100, 100, format: 'png', fallback: "no_image.jpg" %>
        <% if current_user != user %>
          <% if user.followed_by?(current_user) %>
              <%=link_to "フォロー解除", user_relationships_path(user.id), method: :delete, class: "btn smoothScroll anime_test_2" %>
          <% else %>
              <%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn smoothScroll anime_test" %>
          <% end %>
        <% else %>
          <%=link_to "気になる人を探す", users_path, class: "btn smoothScroll anime_test_3" %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>名前</th>
      <th>
        <%= user.name %>
      </th>
    </tr>
    <tr>
      <th>フォロー</th>
      <th>
        <%= link_to follows_user_path(user.id) do %>
          <%= user.followings.count %>
        <% end %>
      </th>
    </tr>
    <tr>
      <th>フォロワー</th>
      <th>
        <%= link_to followers_user_path(user.id) do %>
          <%= user.followers.count %>
        <% end %>
      </th>
    </tr>
  </thead>
</table>

<table class="table">
  <thead>
    <tr>
      <th>自己紹介</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>
        <%= user.introduction %>
      </td>
    </tr>
  </tbody>
</table>

<div>
  <p>
    <%= link_to 'ユーザー情報変更', edit_user_path(user), class: "btn smoothScroll anime" %>
  </p>
</div>

<div>
  <h2 >stady memo</h2>
  <%= form_for(newmemo) do |f| %>

    <p>タイトル</p>
    <%= f.text_field :title %>

    <p>内容詳細</p>
    <%= f.text_area :body %>

    <br><%= f.submit 'Create Memo' %></br>
  <% end %>
</div>

app/views/memos/confirm.html.erb
<%= @newmemo.title %>
<%= @newmemo.body %>

<br>

<%= form_for(@newmemo, url:memos_path) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :body %>
  <%= f.submit '登録する'%>
<% end %>

app/views/memos/edit.html.erb
<%= render 'headfoot/header' %>

<div class="container">
  <div class="row">
    <h2>Memo 編集画面</h2>
    <% if @memo.errors.any? %>
      <h2><%= @memo.errors.count %> errors prohibited this memo from being saved:</h2>

      <ul>
      <% @memo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    <% end %>

    <%= form_for(@memo) do |memo| %>
      <p>カテゴリー</p>
      <%= memo.text_field :category %>

      <p>タイトル</p>
      <%= memo.text_field :title %>

      <p>内容詳細</p>
      <%= memo.text_field :body %>

      <br><%= memo.submit 'Update Memo' %></br>
    <% end %>
  </div>
  <%= render 'headfoot/footer' %>
</div>

app/views/memos/index.html.erb
<%= render 'headfoot/header' %>

<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<% if @newmemo.errors.any? %>
      <h2><%= @newmemo.errors.count %> errors prohibited this memo from being saved:</h2>

      <ul>
      <% @newmemo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'memos/new', user: current_user, newmemo: @newmemo %>
    </div>

    <div class="col-xs-8">
      <h2>全投稿一覧</h2>

      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>タイトル</th>
            <th>内容詳細</th>
            <th><span class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></span></th>
          </tr>
        </thead>

        <tbody>
          <% @memos.each do |memo| %>
            <tr>
              <td></td>
              <td>
                <%= link_to memo_path(memo.id) do %>
                  <%= memo.title %>
                <% end %>
              </td>
              <td>
                <%= memo.body %>
              </td>
              <td>
                <div id="likes_buttons_<%= memo.id %>">
                  <%= render 'memos/favo', memo: memo %>
                </div>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render 'headfoot/topback' %>
  <%= render 'headfoot/footer' %>
</div>

app/views/memos/new.html.erb
<h2>stady memo</h2>

<%= form_for(@newmemo, url: confirm_memos_path) do |f| %>

  <p>タイトル</p>
  <%= f.text_field :title %>

  <p>内容詳細</p>
  <%= f.text_area :body %>

  <br><%= f.submit 'Create Check Memo' %></br>
<% end %>

app/views/memos/show.html.erb
<%= render 'headfoot/header' %>

<% if flash[:notice] %>
  <div class="flash">
    <%= flash[:notice] %>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-xs-4">
      <%= render 'memos/new', user: @user ,newmemo: @newmemo %>
    </div>

    <div class="col-xs-8">
      <h2>ユーザー投稿詳細</h2>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>題名</th>
            <th>平均点</th>
            <th>作成日時</th>
            <th>内容詳細</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= attachment_image_tag @user,:profile_image, :fill, 50, 50, format: 'png', fallback: "no_image.jpg", size:'50x50' %></td>
            <td><%= @memo.title %></td>
            <td><%= @ave.round(1) %></td>
            <td><%= @memo.created_at.strftime('%Y/%m/%d') %></td>
            <td><%= @memo.body %></td>
            <td>
              <% if @memo.user == current_user %>
                <%= link_to "編集する", edit_memo_path(@memo) %>
                <%= link_to "削除する", memo_path(@memo.id), method: :delete, "data-confirm" => "本当に削除しますか？" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>

      <div id="likes_buttons_<%= @memo.id %>">
        <%= render 'memos/favo', memo: @memo %>
      </div>

      <br>

      <%= form_with model:[@memo, @memo_comment] do |f| %>

        <% if @memo_comment.errors.any? %>
          <h2><%= @memo_comment.errors.count %> errors prohibited this memo from being saved:</h2>

          <ul>
            <% @memo_comment.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        <% end %>

        <div id="rateYo"></div>
        <%= f.hidden_field :rates, id: "score" %>
        <br>
        <%= f.text_field :comment,placeholder: "コメントをここに", class: "col-xs-12 text_field" %>
        <div class="col-xs-9"></div>
        <%= f.submit "コメントする", class: "col-xs-3" %>
      <% end %>

      <br>
      <br>
      <br>
      <br>

      <h3>コメント一覧</h3>
      <table class="table">
        <thead>
          <tr>
            <th></th>
            <th>名前</th>
            <th>点数</th>
            <th>日時</th>
            <th>コメント内容</th>
            <th></th>
          </tr>
        </thead>
        <tbody id="comments_index">
          <%= render 'memos/comment', memo: @memo %>
        </tbody>
      </table>
    </div>
  </div>
  <%= render 'headfoot/topback' %>
  <%= render 'headfoot/footer' %>
</div>