config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # ネスト(入れ子)した形に変更 + フォロー一覧、フォロワー一覧の画面も用意
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
    resource :favorites, only: [:index]
  end

  resources :memos do
    collection do
    post :confirm
    # post :new, path: :new, as: :new, action: :back
  end
    resources :memo_comments, only: [:create, :destroy]
    resource :favorites, only: [:index, :create, :destroy]
  end

  get 'searchs/search' => 'searchs#search', as: :search

  resources :homes, only: [:top ,:show]
  root to: 'homes#top'
  get '/home/about' => 'homes#show', as: :about
  resources :maps, only: [:create, :index, :show, :edit, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :memo
end

app/models/memo.rb
class Memo < ApplicationRecord
  belongs_to :user
  has_many :memo_comments, dependent: :destroy
  has_many :favorites ,dependent: :destroy
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { maximum: 200 }

  def self.search(method,word)
    if method == "1" #部分一致
      @memos = Memo.where("title LIKE?","%#{word}%")
    elsif method == "2" #完全一致
      @memos = Memo.where("title LIKE?","#{word}")
    elsif method == "3" #前方一致
      @memos = Memo.where("title LIKE?","#{word}%")
    elsif method == "4" #後方一致
      @memos = Memo.where("title LIKE?","%#{word}")
    else
      @memos = Memo.all
    end
  end
end

app/models/memo_comment.rb
class MemoComment < ApplicationRecord
  belongs_to :user
  belongs_to :memo
  validates :comment, presence: true, length: { maximum: 200 }

  validates :rates, numericality: {
    less_than_or_equal_to: 5.0,
    greater_than_or_equal_to: 0.0
  }
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  # とりあえず、Userモデルと言う呼び方はやめてFollowing, Followerと言うモデル名に変更したい
  # :class_name 関連するモデルクラス名を指定。関連名と参照先のクラス名を分けたい場合に使う("元々の親モデル名"は文字列なのに注意！)
  belongs_to :following, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :memos ,dependent: :destroy
  has_many :memo_comments ,dependent: :destroy
  has_many :favorites ,dependent: :destroy

  attachment :profile_image
  validates :name, presence: true, length: { in: 1..15 }
  validates :introduction, length: { maximum: 50 }


  # フォローする側、される側ふた通りの中間テーブルの名前を再定義
  # has_many :active_relationships, class_name: "Relationship"
  # has_many :passive_relationships, class_name: "Relationship"
  # ↑はNG 親モデルの外部キーがなんなのかという情報が足りない

  # :foreign_key - 参照先のテーブルの外部キーのカラム名を指定できる

  # ====================自分がフォローしているユーザーとの関連 ===================================
  #フォローする側のUserから見て、フォローされる側のUserを(中間テーブルを介して)集める。なので親はfollowing_id(フォローする側)
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  # 中間テーブルを介して「follower」モデルのUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower
  # ========================================================================================

  # ====================自分がフォローされるユーザーとの関連 ===================================
  #フォローされる側のUserから見て、フォローしてくる側のUserを(中間テーブルを介して)集める。なので親はfollower_id(フォローされる側)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  # 中間テーブルを介して「following」モデルのUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following
  # =======================================================================================

  def followed_by?(user)
    # 今自分(引数のuser)がフォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: user.id).present?
  end

  def self.search(method,word)
    if method == "1" #部分一致
      @users = User.where("name LIKE?","%#{word}%")
    elsif method == "2" #完全一致
      @users = User.where("name LIKE?","#{word}")
    elsif method == "3" #前方一致
      @users = User.where("name LIKE?","#{word}%")
    elsif method == "4" #後方一致
      @users = User.where("name LIKE?","%#{word}")
    else
      @users = User.all
    end
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def show
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def create
  end

  def index
  end

  def show
  end

  def edit
  end

  def update
  end

  def destroy
  end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show, :edit]
  def new
    @newmemo = Memo.new
  end

  def confirm
    @newmemo = Memo.new(memo_params)
    return if @newmemo.valid?
  end

  def back
    @newmemo = Memo.new(memo_params)
    render :new
  end

  def create
    @newmemo = Memo.new(memo_params)
    @newmemo.user_id = current_user.id
    if @newmemo.save
      flash[:notice] = "新規登録しました！"
      redirect_to memo_path(@newmemo)
    else
      @memos = Memo.all
      render :index
    end
  end

  def index
    @newmemo = Memo.new
    @memos = Memo.search(params[:method],params[:word])
  end

  def show
    @newmemo = Memo.new
    @memo = Memo.find(params[:id])
    @user = @memo.user
    @memo_comment = MemoComment.new

    comments = @memo.memo_comments
    ratessum = 0
    comments.each do |comment|
      ratessum += comment.rates
    end
    @ave = comments.length == 0 ? 0
    : ratessum / comments.length
  end


  def edit
    @memo = Memo.find(params[:id])
    if @memo.user_id != current_user.id
      redirect_to memos_path
    else
      render :edit
    end
  end
  def update
    @memo = Memo.find(params[:id])
    if @memo.update(memo_params)
      flash[:notice] = "編集しました！"
      redirect_to memo_path(@memo)
    else
      render :edit
    end
  end

  def destroy
    @memo = Memo.find(params[:id])
    @memo.destroy
    flash[:notice] = "削除しました！"
    redirect_to memos_path
  end

  private
  def memo_params
    params.require(:memo).permit(:title, :body ,:user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:index, :show ,:edit]
  def index
    @newmemo = Memo.new
    @users = User.search(params[:method],params[:word])
  end

  def show
    @newmemo = Memo.new
    @user = User.find(params[:id])
    @memos = @user.memos
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "編集しました！"
      redirect_to user_path(@user)
    else
      render :edit
    end
  end

  def follows
    @newmemo = Memo.new
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    @newmemo = Memo.new
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :profile_image, :introduction)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/memo_comments_helper.rb
module MemoCommentsHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/searchs_helper.rb
module SearchsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/headfoot/_footer.html.erb
<footer class="navbar-right">
  <div>©.inc</div>
</footer>

app/views/headfoot/_header.html.erb
<div id="sp-menu">
  <h2>myBrain</h2>
  <ul>
    <% if user_signed_in? %>
    <li class="">
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-th" aria-hidden="true"></span> TOP
        <% end %>
      </li>
      <li class="">
        <%= link_to user_path(current_user.id) do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span> マイページ
        <% end %>
      </li>
        <li class="">
          <%= link_to users_path do %>
            <span class="glyphicon glyphicon-user" aria-hidden="true"></span> ユーザー
          <% end %>
      </li>
      <li class="">
        <%= link_to memos_path do %>
          <span class="glyphicon glyphicon-book" aria-hidden="true"></span> 投稿
        <% end %>
      </li>
      <li class="">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span> ログアウト
        <% end %>
      </li>
      <li>
          <%= form_tag search_path, :method => 'get' do %>
            <div class="text-align">
              <%= select_tag "table", options_for_select({"ユーザー" => "1", "投稿タイトル" => "2"}), class: "search" %>
              <%= select_tag "method", options_for_select({"部分一致" => "1", "完全一致" => "2", "前方一致" => "3", "後方一致" => "4"}), class: "search" %>
              <%= text_field_tag :word,"",{placeholder: :"検索するキーワード", class: ""} %>
              <%= submit_tag "検索する", :name => nil, class: "btn btn-default" %>
            </div>
          <% end %>
      </li>

    <% else %>
      <li class="">
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-th" aria-hidden="true"></span> TOP
        <% end %>
      </li>
      <li class="">
        <%= link_to root_path do %>
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span> HOME
        <% end %>
      </li>
      <li class="">
        <%= link_to about_path do %>
          <span class="glyphicon glyphicon-link" aria-hidden="true"></span> サイト紹介
        <% end %>
      </li>
      <li class="">
        <%= link_to new_user_registration_path do %>
          <span class="glyphicon glyphicon-check" aria-hidden="true"></span> 新規登録
        <% end %>
      </li>
      <li class="">
        <%= link_to new_user_session_path do %>
          <span class="glyphicon glyphicon-log-in" aria-hidden="true"></span>  ログイン
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

<div id="hm-icon">
  <a class="menu-trigger" href="#">
    <span></span>
    <span></span>
    <span></span>
  </a>
</div>

app/views/headfoot/_topback.html.erb
<span id="back">
  <a href="#">
    <%= image_tag "arrow.png" %>
  </a>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ZZ</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <!-- turbolinksが原因の可能性の時外してみる -->
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>